# Generated by Django 6.0.1 on 2026-01-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('place_url', models.URLField()),
                ('pick_count', models.IntegerField(default=0)),
                ('last_picked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
